server:
  port: 8081
  servlet:
    context-path: /api

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8082/oauth/check_token/

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3316/registration-database
    username: root
    password: P@ssw0rd
