server:
  port: 8082

spring:
  security:
    user:
      name: john
      password: P@ssw0rd

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: clientSecret
      authorized-grant-types: authorization_code, refresh_token, password
      scope: openid
